[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.60"
resvg = "0.28.0"
tiny-skia = "0.8.2"
usvg = "0.28.0"
format_xml = "0.3.0"
hex_color = "2.0.0"
